export const de = {
  common: {
    languages: {
      english: 'Englisch',
      hungarian: 'Ungarisch',
      german: 'Deutsch',
      romanian: 'Rumänisch',
    },
    calendar: 'Kalender',
    home: 'Startseite',
    create: 'Erstellen',
    language: 'Sprache',
    events: 'Veranstaltungen',
    loading: 'Laden...',
    error: 'Fehler aufgetreten',
    couldntLoadEvents: 'Veranstaltungen konnten nicht geladen werden',
    couldntLoadEvent: 'Veranstaltung konnte nicht geladen werden',
    couldntLoadParticipants: 'Teilnehmer konnten nicht geladen werden',
  },
  event: {
    title: 'Titel',
    location: 'Ort',
    date: 'Datum',
    time: 'Uhrzeit',
    description: 'Beschreibung',
    online: 'Online',
    offline: 'Offline',
    createEvent: 'Veranstaltung erstellen',
    updateEvent: 'Veranstaltung bearbeiten',
    deleteEvent: 'Veranstaltung löschen',
    confirmDelete: 'Möchten Sie diese Veranstaltung wirklich löschen?',
  },
  participant: {
    participants: 'Teilnehmer',
    addParticipant: 'Teilnehmer hinzufügen',
    deleteParticipant: 'Teilnehmer löschen',
    confirmDeleteParticipant: 'Möchten Sie diesen Teilnehmer wirklich löschen?',
    noParticipants: 'Noch keine Teilnehmer',
    name: 'Name',
    email: 'E-Mail',
  },
  buttons: {
    add: 'Hinzufügen',
    create: 'Erstellen',
    update: 'Aktualisieren',
    delete: 'Löschen',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
  },
  filter: {
    apply: 'Filter anwenden',
    title: 'Titel',
    minDate: 'Min. Datum',
    maxDate: 'Max. Datum',
    minTime: 'Min. Zeit',
    maxTime: 'Max. Zeit',
    online: 'Online',
  },
};
