export const en = {
  common: {
    languages: {
      english: 'English',
      hungarian: 'Magyar',
      german: 'Deutsch',
      romanian: 'Română',
    },
    calendar: 'Calendar',
    home: 'Home',
    create: 'Create',
    language: 'Language',
    events: 'Events',
    loading: 'Loading...',
    error: 'Error occurred',
    couldntLoadEvents: "Couldn't load events",
    couldntLoadEvent: "Couldn't load event",
    couldntLoadParticipants: "Couldn't load participants",
  },
  event: {
    title: 'Title',
    location: 'Location',
    date: 'Date',
    time: 'Time',
    description: 'Description',
    online: 'Online',
    offline: 'Offline',
    createEvent: 'Create Event',
    updateEvent: 'Update Event',
    deleteEvent: 'Delete Event',
    confirmDelete: 'Are you sure you want to delete this event?',
  },
  participant: {
    participants: 'Participants',
    addParticipant: 'Add Participant',
    deleteParticipant: 'Delete Participant',
    confirmDeleteParticipant: 'Are you sure you want to delete this participant?',
    noParticipants: 'No participants yet',
    name: 'Name',
    email: 'Email',
  },
  buttons: {
    add: 'Add',
    create: 'Create',
    update: 'Update',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  filter: {
    apply: 'Apply filter',
    title: 'Title',
    minDate: 'Min date',
    maxDate: 'Max date',
    minTime: 'Min time',
    maxTime: 'Max time',
    online: 'Online',
  },
};
