export const hu = {
  common: {
    languages: {
      english: 'Angol',
      hungarian: 'Magyar',
      german: 'Német',
      romanian: 'Román',
    },
    calendar: 'Naptár',
    home: 'Kezdőlap',
    create: 'Létrehozás',
    language: 'Nyelv',
    events: 'Események',
    loading: 'Betöltés...',
    error: 'Hiba történt',
    couldntLoadEvents: 'Nem sikerült betölteni az eseményeket',
    couldntLoadEvent: 'Nem sikerült betölteni az eseményt',
    couldntLoadParticipants: 'Nem sikerült betölteni a résztvevőket',
  },
  event: {
    title: 'Cím',
    location: 'Helyszín',
    date: 'Dátum',
    time: 'Időpont',
    description: 'Leírás',
    online: 'Online',
    offline: 'Személyes',
    createEvent: 'Esemény létrehozása',
    updateEvent: 'Esemény módosítása',
    deleteEvent: 'Esemény törlése',
    confirmDelete: 'Biztosan törölni szeretné ezt az eseményt?',
  },
  participant: {
    participants: 'Résztvevők',
    addParticipant: 'Résztvevő hozzáadása',
    deleteParticipant: 'Résztvevő törlése',
    confirmDeleteParticipant: 'Biztosan törölni szeretné ezt a résztvevőt?',
    noParticipants: 'Még nincsenek résztvevők',
    name: 'Név',
    email: 'E-mail cím',
  },
  buttons: {
    add: 'Hozzáadás',
    create: 'Létrehozás',
    update: 'Módosítás',
    delete: 'Törlés',
    cancel: 'Mégse',
    confirm: 'Megerősítés',
  },
  filter: {
    apply: 'Szűrés',
    title: 'Cím',
    minDate: 'Min. dátum',
    maxDate: 'Max. dátum',
    minTime: 'Min. időpont',
    maxTime: 'Max. időpont',
    online: 'Online',
  },
};
