export const ro = {
  common: {
    languages: {
      english: 'Engleză',
      hungarian: 'Maghiară',
      german: 'Germană',
      romanian: 'Română',
    },
    calendar: 'Calendar',
    home: 'Acasă',
    create: 'Creare',
    language: 'Limbă',
    events: 'Evenimente',
    loading: 'Se încarcă...',
    error: 'Eroare',
    couldntLoadEvents: 'Nu s-au putut încărca evenimentele',
    couldntLoadEvent: 'Nu s-a putut încărca evenimentul',
    couldntLoadParticipants: 'Nu s-au putut încărca participanții',
  },
  event: {
    title: 'Titlu',
    location: 'Locație',
    date: 'Data',
    time: 'Ora',
    description: 'Descriere',
    online: 'Online',
    offline: 'Offline',
    createEvent: 'Creare eveniment',
    updateEvent: 'Actualizare eveniment',
    deleteEvent: 'Ștergere eveniment',
    confirmDelete: 'Sigur doriți să ștergeți acest eveniment?',
  },
  participant: {
    participants: 'Participanți',
    addParticipant: 'Adăugare participant',
    deleteParticipant: 'Ștergere participant',
    confirmDeleteParticipant: 'Sigur doriți să ștergeți acest participant?',
    noParticipants: 'Încă nu există participanți',
    name: 'Nume',
    email: 'Email',
  },
  buttons: {
    add: 'Adaugă',
    create: 'Crează',
    update: 'Actualizează',
    delete: 'Șterge',
    cancel: 'Anulează',
    confirm: 'Confirmă',
  },
  filter: {
    apply: 'Aplică',
    title: 'Titlu',
    minDate: 'Data minimă',
    maxDate: 'Data maximă',
    minTime: 'Ora minimă',
    maxTime: 'Ora maximă',
    online: 'Online',
  },
};
